add effector
i-obraztsov/storeon-redux-compare pull request #1
Opened 2021-07-14 08:21 UTC by i-obraztsov

2021-07-14 17:46 UTC, funsis requested changes

2021-07-14 17:46 UTC, funsis commented on effector/features/picker.js
> +const $subreddit = createStore("reactjs").on(
Используй restore https://effector.dev/docs/api/effector/restore/#restoreevent-defaultstate

2021-07-14 17:46 UTC, funsis commented on effector/features/picker.js
> +const $posts = createStore([]).on(fetchPostsFx.doneData, (_, result) => result);
И тут restore

2021-07-14 17:46 UTC, funsis commented on effector/features/picker.js
> +const $postsBySubreddit = createStore({}).on(fetchPostsFx.doneData, (state, result) => {
А зачем нужен еще и такой стор?

2021-07-14 17:46 UTC, funsis commented on effector/features/picker.js
> +forward({
Не очень понял какую проблему ты пытаешься решить через этот forward?

2021-07-14 17:46 UTC, funsis commented on effector/App.js
> +    subredditChanged()
Опиши плез, какую проблему ты пытаешься решить через этот эффект? Вообще, хорошая практика на мой взгляд, не импортировать эффекты из модели а только сторы и обычные ивенты

2021-07-14 18:27 UTC, i-obraztsov commented on effector/features/picker.js
> +const $subreddit = createStore("reactjs").on(
ага, про restore знаю

2021-07-14 18:31 UTC, i-obraztsov commented on effector/features/picker.js
> +const $postsBySubreddit = createStore({}).on(fetchPostsFx.doneData, (state, result) => {
Это я немного не доделал, это нужно типа для кеша. Там будет объект вида { [reactjs|frontend]: data } и если данные не обновились то брать из этого объекта

2021-07-14 18:44 UTC, i-obraztsov commented on effector/App.js
> +    subredditChanged()
Здесь нужно при инициализации приложения загрузить данные и в эффект 
```
fetchPostsFx:
const fetchPostsFx = createEffect((subreddit) =>
  fetch(`https://www.reddit.com/r/${subreddit}.json`)
    .then((req) => req.json())
    .then(({ data }) => data.children.map((child) => child.data))
);
```
нужно пробросить стейт `$subreddit` чтобы в урле не получился `undefined`

И я тут не знаю как лучше сделать, использовать эффект или как щас сделано через эвент

2021-07-14 18:46 UTC, i-obraztsov commented on effector/features/picker.js
> +const $subreddit = createStore("reactjs").on(
Я так сделал, чтобы когда рассказывать было нагляднее )

2021-07-15 05:59 UTC, i-obraztsov commented on effector/App.js
> +    subredditChanged()
А если не экспортировать effect то как тогда например взять переменную pending, хотя вроде в примерах из доки она используется в компоненте: https://effector.dev/ru/docs/recipes/react/example-effects/

2021-07-20 11:42 UTC, funsis requested changes

2021-07-20 11:42 UTC, funsis commented on effector/model/subreddit.js
> +const $isFetching = restore(fetchPostsFx.pending, false);
тут не нужен restore, pending у эффекта эту уже стор, достаточно `const $isFetching = fetchPostsFx.pending`

2021-07-22 05:14 UTC, merged